### ISSUE TITLE
Perhaps related or not with CleanWin: Winget doesn't work

### ISSUE THREAD

**Issue by KriiXOne** [pratyakshm/CleanWin#23]
I run a fresh windows 10 Pro install this morning using the latest MediaCreationTool, other than that i didn't do nothing but update to the latest versions with WindowsUpdate. then i run CLI.exe and let CleanWin do all the work,
one reboot later and trying winget, it does not work, as shown at: https://github.com/microsoft/winget-cli/issues/1103

**Comment by pratyakshm** [comment]
Investigating at https://github.com/microsoft/winget-cli/issues/1103

**Comment by pratyakshm** [comment]
Issue identified to be caused by CleanWin

**Comment by pratyakshm** [comment]
https://github.com/pratyakshm/CleanWin/commit/1d1a98fd1497865befb1c8eafe85b31a388ed6c4 fixes this issue. Thank you for reporting.
