### ISSUE TITLE
CleanWin breaks installation of EarTrumpet (and other appinstaller apps)

### ISSUE THREAD

**Issue by riverar** [pratyakshm/CleanWin#26]
Hey @pratyakshm, how could you do this to me?

## Steps to reproduce
1. Run CleanWin, bypassing 14 anti-virus prompts warning me to not do so
2. Attempt to install EarTrumpet (`ms-appinstaller:?source=https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller`)
3. Observe the crime

## Screenshots

![image](https://user-images.githubusercontent.com/475132/122508483-e81acc80-cfb6-11eb-9179-42bdad8b7aea.png)

![image](https://user-images.githubusercontent.com/475132/122508404-cfaab200-cfb6-11eb-8768-b91920ca42d7.png)

**Comment by pratyakshm** [comment]
duplicate issue old man :(
originally filed here: https://github.com/pratyakshm/CleanWin/issues/23

**Comment by pratyakshm** [comment]
Not a duplicate, but a related issue
I woke up 10 minutes ago, my brain's still rebooting.
apologies for messing up
