### ISSUE TITLE
Feature Request: Add option to disable  Win defender

### ISSUE THREAD

**Issue by FireHound-lab** [pratyakshm/CleanWin#29]
### Does your feature request involve usage of third party software?

No

### Have you written the code for it?

No

### Explain the feature

Some peeps don't like win defender so..

### Does this Feature Request follow CleanWin principles?

- [X] Yes

**Comment by pratyakshm** [comment]
![image](https://user-images.githubusercontent.com/54220235/126441331-80b30315-0a23-4da7-8c24-070139e3707d.png)
[Principles](https://github.com/pratyakshm/CleanWin/wiki/Principles)
