### ISSUE TITLE
Enable Hyper-V platform in WSL additions

### ISSUE THREAD

**Issue by tushar4303** [pratyakshm/CleanWin#3]

**Comment by pratyakshm** [comment]
@tushar4303 ah yes, i did that to keep myself reminded

**Comment by pratyakshm** [comment]
@pratyakshm wtf bhosdike

**Comment by pratyakshm** [comment]
https://github.com/pratyakshm/CleanWin/commit/465ef29edd623d2bb70c98ca2e35a662417ba088 added, issue closed.
