### ISSUE TITLE
Add option to uninstall OneNote / OneNote for windows 10

### ISSUE THREAD

**Issue by wanderlusttt** [pratyakshm/CleanWin#59]
### WinRice principles

- [x] I have read the WinRice principles and I believe that this feature request abides by the WinRice principles to my truest sense.

### Explain the feature.

Add option to uninstall OneNote / OneNote for windows 10 as many of the users don't use it and why should we even keep this bloatware on the machine.

### Does your feature request involve usage of third party software?

No

**Comment by pratyakshm** [comment]
Hey, OneNote for Windows 10 / OneNote (UWP) is already included in the uninstaller list.
They are uninstalled when you choose to uninstall apps without selecting them. Check https://github.com/pratyakshm/WinRice/blob/main/WinRice.ps1#L1611.

Did you choose to uninstall a preset list of apps, or did you choose to select which apps to uninstall?

**Comment by pratyakshm** [comment]
@blackpanther-007 that's interesting. Do you mind opening a bug report and including your transcript in it?
