### ISSUE TITLE
[Request] A better UWP 'crapware' removal

### ISSUE THREAD

**Issue by AvinashReddy3108** [pratyakshm/CleanWin#7]
![Here's a screenshot from the Sophia script](https://camo.githubusercontent.com/949d194033a2a95571d78d99d83522d770aded8c73a4dbb717eb72e3c6bafee8/68747470733a2f2f692e696d6775722e636f6d2f4158593132614a2e706e67)

Instead of [hard-coding the package names](https://github.com/pratyakshm/CleanWin/blob/main/CleanWin-GUI.ps1#L464-L493) of the UWP crapware to remove, let's provide users the ability to choose what to remove, as seen in the screenshot above (it's from the [Sophia script](https://github.com/farag2/Windows-10-Sophia-Script), by @farag2).

Another upside of this method would be that we won't need to maintain a list of packages to remove, as it's always dynamically populated, which for me (and hopefully others) is a `CleanWin`-win (get it? :rofl: )

**Comment by pratyakshm** [comment]
@AvinashReddy3108 LMFAO, THANK YOU SO MUCH BAHI @AvinashReddy3108 NOHOMO

**Comment by pratyakshm** [comment]
Thanks, e908c51b63c182cad1a004389f02c50c1e08b4aa addresses this issue.

**Comment by farag2** [comment]
Indeed the GUI form was totally written by @oz-zo :) Also someday I'll implement this stuff: https://github.com/farag2/Windows-10-Sophia-Script/issues/56

**Comment by pratyakshm** [comment]
> Indeed the GUI form was totally written by @oz-zo :) Also someday I'll implement this stuff: [farag2/Windows-10-Sophia-Script#56](https://github.com/farag2/Windows-10-Sophia-Script/issues/56)

Nice, that's really cool, I will be looking forward to [this](https://github.com/farag2/Windows-10-Sophia-Script/issues/56). I agree with that the user has to say, although its technical it might be difficult for some to figure out what a certain app is, for instance Cortana is Microsoft.549981C3F5F10.
